IN_CHANNELS = 4 # change to 3 if not using edge channel
NUM_EPOCHS = 300
BATCH_SIZE = 16
NUM_VAL = 10 # number of images during validation
NUM_TEST = 50 # number of images during testing
EXP_NAME = 'trial'
GPU_ID = '1'
DATAROOT = 'dataset/'
DIS_FREQ = NUM_EPOCHS//100
COLOR_NAME = 'blurred_images'
BW_NAME = 'hed'
